<a href="https://colab.research.google.com/github/Word-Wizards/Neural-NLP/blob/Word2Vac/NLP_30sep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import os
import random
import tensorflow as tf

In [ ]:
df = pd.read_json('H:/M-tech(ICT)/M-tech(ICT) 3 SEM/Neural NLP/Assignment 1/new/dataset.gz', lines=True, compression='gzip')

In [ ]:
df.head()

id      source version                     added  \
0  254721023  s2ag/valid      v1  2022-12-16T16:07:05.559Z   
1  254200673  s2ag/valid      v1  2022-12-04T16:21:43.441Z   
2  252643161  s2ag/valid      v1  2022-10-01T15:18:53.788Z   
3  244852373  s2ag/valid      v1  2021-12-04T16:21:39.980Z   
4  254774363  s2ag/valid      v1  2022-12-17T16:19:10.635Z   

                    created                                               text  
0  2022-12-14T00:00:00.000Z  Investigation Some Characteristics of Biocompo...  
1  2022-12-02T00:00:00.000Z  Modelling Techniques for Conjunctive Water Man...  
2  2022-12-01T00:00:00.000Z  Complete Targets Coverage in Energy Harvesting...  
3  2022-12-01T00:00:00.000Z  Nonorthogonal Multiple Access Enabled Two-Way ...  
4  2022-12-14T00:00:00.000Z  106 A CASE OF COMPLETE ATRIOVENTRICULAR BLOCK ...

In [ ]:
df.size

667368

In [ ]:
df_train=df[:3000]

In [ ]:
df_train.shape

(3000, 6)

In [ ]:
df_train

id      source version                     added  \
0     254721023  s2ag/valid      v1  2022-12-16T16:07:05.559Z   
1     254200673  s2ag/valid      v1  2022-12-04T16:21:43.441Z   
2     252643161  s2ag/valid      v1  2022-10-01T15:18:53.788Z   
3     244852373  s2ag/valid      v1  2021-12-04T16:21:39.980Z   
4     254774363  s2ag/valid      v1  2022-12-17T16:19:10.635Z   
...         ...         ...     ...                       ...   
2995  254443613  s2ag/valid      v1  2022-12-09T16:17:15.100Z   
2996  250026872  s2ag/valid      v1  2022-06-26T15:15:06.464Z   
2997  254712765  s2ag/valid      v1  2022-12-16T16:19:29.925Z   
2998  254330861  s2ag/valid      v1  2022-12-07T20:07:48.011Z   
2999  254906011  s2ag/valid      v1  2022-12-21T16:08:34.446Z   

                       created  \
0     2022-12-14T00:00:00.000Z   
1     2022-12-02T00:00:00.000Z   
2     2022-12-01T00:00:00.000Z   
3     2022-12-01T00:00:00.000Z   
4     2022-12-14T00:00:00.000Z   
...                        ...   
2995  2022-12-06T00:00:00.000Z   
2996  2022-12-01T00:00:00.000Z   
2997  2022-12-13T00:00:00.000Z   
2998  2022-12-07T00:00:00.000Z   
2999  2023-01-01T00:00:00.000Z   

                                                   text  
0     Investigation Some Characteristics of Biocompo...  
1     Modelling Techniques for Conjunctive Water Man...  
2     Complete Targets Coverage in Energy Harvesting...  
3     Nonorthogonal Multiple Access Enabled Two-Way ...  
4     106 A CASE OF COMPLETE ATRIOVENTRICULAR BLOCK ...  
...                                                 ...  
2995  Photovoltaic Models’ Parameter Extraction Usin...  
2996  Optical Inline-Sagnac Current Sensor, Part II:...  
2997  Trajectories of ENDS and cigarette use among d...  
2998  Research on UECR air pollutant propagation mod...  
2999  The role of plasma angiotensin-converting enzy...  

[3000 rows x 6 columns]

In [ ]:
df_test=df[3000:4000]

In [ ]:
df_test.shape

(1000, 6)

In [ ]:
df_test

id      source version                     added  \
3000  254917015  s2ag/valid      v1  2022-12-21T16:20:47.730Z   
3001  254626571  s2ag/valid      v1  2022-12-14T16:05:57.440Z   
3002  255322121  s2ag/valid      v1  2023-01-01T16:21:07.339Z   
3003  254558718  s2ag/valid      v1  2022-12-12T16:07:32.557Z   
3004  254903501  s2ag/valid      v1  2022-12-21T16:18:40.402Z   
...         ...         ...     ...                       ...   
3995  254881867  s2ag/valid      v1  2022-12-21T14:09:55.770Z   
3996  255087471  s2ag/valid      v1  2022-12-25T16:14:18.616Z   
3997  254918823  s2ag/valid      v1  2022-12-21T16:07:01.402Z   
3998  254354264  s2ag/valid      v1  2022-12-07T18:08:46.764Z   
3999  254582552  s2ag/valid      v1  2022-12-13T16:03:47.617Z   

                       created  \
3000  2022-12-15T00:00:00.000Z   
3001  2022-12-12T00:00:00.000Z   
3002  2022-12-30T00:00:00.000Z   
3003  2022-12-09T00:00:00.000Z   
3004  2022-12-19T00:00:00.000Z   
...                        ...   
3995  2022-12-01T00:00:00.000Z   
3996  2022-12-22T00:00:00.000Z   
3997  2022-12-18T00:00:00.000Z   
3998  2022-12-01T00:00:00.000Z   
3999  2023-01-01T00:00:00.000Z   

                                                   text  
3000  Geochemical Signatures of Felsic Volcanic Rock...  
3001  ‘Mixed Blood’ and Aesthetic Evolution in China...  
3002  Applying universal design principles to improv...  
3003  Social Exclusion of Women of Civil Victims Of ...  
3004  A progressive change in the virulence spectrum...  
...                                                 ...  
3995  Predicting Conversions from Normal to MCI and ...  
3996  Three-Dimensional Division of Visible Light Co...  
3997  Synthesis and Characterization of Nanoformulat...  
3998  Curcumin Attenuates Lipopolysaccharide-Induced...  
3999  A new hybrid method for mutual coupling minimi...  

[1000 rows x 6 columns]

In [ ]:
!pip install nltk


[notice] A new release of pip is available: 23.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import os
import re
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords

In [ ]:
# Initialize the TF-IDF vectorizer
import nltk
nltk.download('stopwords')
tfidf_vectorizer = TfidfVectorizer(lowercase=False, stop_words=stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DJ\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
import re
import string
import pandas as pd
import numpy as np
import math
from numpy import array
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from sklearn.cluster import KMeans
from collections import Counter
from nltk.stem import WordNetLemmatizer
from nltk import word_tokenize, pos_tag

nltk.download('averaged_perceptron_tagger')
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\DJ\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\DJ\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DJ\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\DJ\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
# Pre-processing function to apply the specified cleanup
def preprocess_text(text):
    # Remove URLs
    text = re.sub(r'http\S+', '', text)

    # Remove bullets, enumerations, hyphens, and punctuation
    text = re.sub(r'[\•\-\d]+', ' ', text)
    text = re.sub(r'[\'\"\,\.\!\?\:\;\(\)\[\]\{\}\<\>]', ' ', text)

    # Convert numerical values to text
    text = re.sub(r'\d+', lambda x: num2words(x.group()), text)

    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    words = word_tokenize(text.lower())
    words = [word for word in words if word not in stop_words]

    # Reconstruct sentences
    text = " ".join(words)

    return text


In [ ]:
data = [doc for doc in df_train['text'].tolist()]

In [ ]:
data[0]

"Investigation Some Characteristics of Biocomposites Coating for Biomedical Implants\n\nThe surface has a vital function in the tissue's response to the presence of foreign material in the field of body implants. Surface modification with coatings can be adjusted to provide the highest service performance at the lowest cost. Coatings can increase corrosion resistance by reducing metal ion and corrosion product migration in the body. We fabricated polymer based bio-composite coatings by blending chitosan (Chi), alginate (Alg) and nanoparticles ((TiO2, Nb2O5) by dip coating onto a 316L stainless steel substrate. The coatings’ surface morphology and phases were studied using FESEM and FTIR analysis. The wettability behavior of the coated samples was also studied by investigating their contact wetting attributes. The antibacterial activity of the functionalized coatings was determined too. The FTIR results showed that the blending of Chi-Alg and nanoparticles was excellent, and no obvious 

In [ ]:
def preprocess_text1(text):
    text = re.sub(r'\d+' , '', text)
    text = remove_punctuation(text)
    text = text.lower()
    text = text.strip()
    text = re.sub(r'\b\w{1,2}\b', '', text)
    tokens = toknizing(text)
    pos_map = {'J': 'a', 'N': 'n', 'R': 'r', 'V': 'v'}
    pos_tags = pos_tag(tokens)
    lemmatiser = WordNetLemmatizer()
    tokens = [lemmatiser.lemmatize(t.lower(), pos=pos_map.get(p[0], 'v')) for t, p in pos_tags]
    return tokens

In [ ]:
def remove_punctuation(text):
     punctuations = '''!()-[]{};:'"\,<>./?@#$%^+&*_~'''
     no_punct = ""
     for char in text:
        if char not in punctuations:
            no_punct = no_punct + char
     return no_punct

In [ ]:
def toknizing(text):
  stop_words = set(stopwords.words('english'))
  tokens = word_tokenize(text)
  result = [i for i in tokens if not i in stop_words]
  return result

In [ ]:
train_sentences = [preprocess_text1(doc) for doc in df_train['text'].tolist()]
test_sentences = [preprocess_text1(doc) for doc in df_test['text'].tolist()]

In [ ]:
for i in range(5):
  print(train_sentences[i])

['investigation', 'characteristic', 'biocomposites', 'coat', 'biomedical', 'implant', 'surface', 'vital', 'function', 'tissue', 'response', 'presence', 'foreign', 'material', 'field', 'body', 'implant', 'surface', 'modification', 'coating', 'adjust', 'provide', 'high', 'service', 'performance', 'low', 'cost', 'coating', 'increase', 'corrosion', 'resistance', 'reduce', 'metal', 'ion', 'corrosion', 'product', 'migration', 'body', 'fabricate', 'polymer', 'base', 'biocomposite', 'coating', 'blend', 'chitosan', 'chi', 'alginate', 'alg', 'nanoparticles', 'tio', 'nbo', 'dip', 'coat', 'onto', 'stainless', 'steel', 'substrate', 'coating', '’', 'surface', 'morphology', 'phase', 'study', 'use', 'fesem', 'ftir', 'analysis', 'wettability', 'behavior', 'coat', 'sample', 'also', 'study', 'investigate', 'contact', 'wet', 'attribute', 'antibacterial', 'activity', 'functionalized', 'coating', 'determine', 'ftir', 'result', 'show', 'blend', 'chialg', 'nanoparticles', 'excellent', 'obvious', 'difference',

#returning sentences instead of tokens

In [ ]:
# Tokenize and preprocess the documents into sentences
def tokenize_and_preprocess(document):
    sentences = re.split(r'(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?|\!)\s', document)
    sentences = [preprocess_text(sentence) for sentence in sentences if sentence.strip()]
    return sentences

In [ ]:
train_sentences = [tokenize_and_preprocess(doc) for doc in df_train['text'].tolist()]
test_sentences = [tokenize_and_preprocess(doc) for doc in df_test['text'].tolist()]

In [ ]:
train_sentences[0]

['investigation characteristics biocomposites coating biomedical implants surface vital function tissue response presence foreign material field body implants',
 'surface modification coatings adjusted provide highest service performance lowest cost',
 'coatings increase corrosion resistance reducing metal ion corrosion product migration body',
 'fabricated polymer based bio composite coatings blending chitosan chi alginate alg nanoparticles tio nb dip coating onto l stainless steel substrate',
 'coatings ’ surface morphology phases studied using fesem ftir analysis',
 'wettability behavior coated samples also studied investigating contact wetting attributes',
 'antibacterial activity functionalized coatings determined',
 'ftir results showed blending chi alg nanoparticles excellent obvious differences spectra changes structures polymer matrices observed',
 'sem results demonstrated coating layers uniform homogeneous crack free l stianless steel substrate using tio nb nano particles',


In [ ]:
combined_list = [item for sublist in train_sentences for item in sublist]

In [ ]:
combined_list[0]

'investigation characteristics biocomposites coating biomedical implants surface vital function tissue response presence foreign material field body implants'

In [ ]:
len(combined_list)

26747

In [ ]:
import os
import re
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords

In [ ]:
# Initialize the TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer(lowercase=False, stop_words=stopwords.words('english'))

In [ ]:
# TD-IDF Matrix
X = tfidf_vectorizer.fit_transform(combined_list)

# extracting feature names
tfidf_tokens = tfidf_vectorizer.get_feature_names_out()

In [ ]:
tfidf_tokens

array(['_group', 'aa', 'aaa', ..., 'flow', 'fluid', '𝛿𝑡'], dtype=object)

In [ ]:
import pandas as pd

result = pd.DataFrame(
    data=X.toarray(),
    index=[X for X in combined_list],
    columns=tfidf_tokens
)

result

_group   aa  aaa  aacr  \
investigation characteristics biocomposites coa...     0.0  0.0  0.0   0.0   
surface modification coatings adjusted provide ...     0.0  0.0  0.0   0.0   
coatings increase corrosion resistance reducing...     0.0  0.0  0.0   0.0   
fabricated polymer based bio composite coatings...     0.0  0.0  0.0   0.0   
coatings ’ surface morphology phases studied us...     0.0  0.0  0.0   0.0   
...                                                    ...  ...  ...   ...   
negative significant correlation found e gfr ck...     0.0  0.0  0.0   0.0   
additionally also significant correlations plas...     0.0  0.0  0.0   0.0   
significant positive correlation also found pla...     0.0  0.0  0.0   0.0   
conclusions significant correlation plasma ace ...     0.0  0.0  0.0   0.0   
investigation revealed statistically significan...     0.0  0.0  0.0   0.0   

                                                    aada  aapc  aaron  aas  \
investigation characteristics biocomposites coa...   0.0   0.0    0.0  0.0   
surface modification coatings adjusted provide ...   0.0   0.0    0.0  0.0   
coatings increase corrosion resistance reducing...   0.0   0.0    0.0  0.0   
fabricated polymer based bio composite coatings...   0.0   0.0    0.0  0.0   
coatings ’ surface morphology phases studied us...   0.0   0.0    0.0  0.0   
...                                                  ...   ...    ...  ...   
negative significant correlation found e gfr ck...   0.0   0.0    0.0  0.0   
additionally also significant correlations plas...   0.0   0.0    0.0  0.0   
significant positive correlation also found pla...   0.0   0.0    0.0  0.0   
conclusions significant correlation plasma ace ...   0.0   0.0    0.0  0.0   
investigation revealed statistically significan...   0.0   0.0    0.0  0.0   

                                                    aats  aav  ...  final  find  \
investigation characteristics biocomposites coa...   0.0  0.0  ...   0.0  0.0   
surface modification coatings adjusted provide ...   0.0  0.0  ...   0.0  0.0   
coatings increase corrosion resistance reducing...   0.0  0.0  ...   0.0  0.0   
fabricated polymer based bio composite coatings...   0.0  0.0  ...   0.0  0.0   
coatings ’ surface morphology phases studied us...   0.0  0.0  ...   0.0  0.0   
...                                                  ...  ...  ...   ...  ...   
negative significant correlation found e gfr ck...   0.0  0.0  ...   0.0  0.0   
additionally also significant correlations plas...   0.0  0.0  ...   0.0  0.0   
significant positive correlation also found pla...   0.0  0.0  ...   0.0  0.0   
conclusions significant correlation plasma ace ...   0.0  0.0  ...   0.0  0.0   
investigation revealed statistically significan...   0.0  0.0  ...   0.0  0.0   

                                                    first  fixed  fixes  flight  \
investigation characteristics biocomposites coa...   0.0   0.0   0.0    0.0   
surface modification coatings adjusted provide ...   0.0   0.0   0.0    0.0   
coatings increase corrosion resistance reducing...   0.0   0.0   0.0    0.0   
fabricated polymer based bio composite coatings...   0.0   0.0   0.0    0.0   
coatings ’ surface morphology phases studied us...   0.0   0.0   0.0    0.0   
...                                                  ...   ...   ...    ...   
negative significant correlation found e gfr ck...   0.0   0.0   0.0    0.0   
additionally also significant correlations plas...   0.0   0.0   0.0    0.0   
significant positive correlation also found pla...   0.0   0.0   0.0    0.0   
conclusions significant correlation plasma ace ...   0.0   0.0   0.0    0.0   
investigation revealed statistically significan...   0.0   0.0   0.0    0.0   

                                                    flocks  flow  fluid   𝛿𝑡  
investigation characteristics biocomposites coa...    0.0  0.0   0.0  0.0  
surface modification coatings adjusted provide ...    0.0  0.0   0.0  0.0  
coatings increase corrosion 

In [ ]:
import numpy as np
from sklearn.decomposition import TruncatedSVD

# Assume your context matrix is represented as a NumPy array called 'context_matrix'
# Each row in context_matrix represents a sentence

# Define the number of components for SVD (the desired dimension of your embeddings)
n_components = 100  # You can adjust this based on your requirements

# Initialize the SVD model
svd = TruncatedSVD(n_components=n_components)

# Fit SVD to your context matrix
sentence_embeddings = svd.fit_transform(X)

# 'sentence_embeddings' now contains the embeddings for each row (sentence) in the context matrix

# You can use these embeddings for various NLP tasks, like semantic similarity, clustering, etc.

In [ ]:
sentence_embeddings.size

2674700

In [ ]:
sentence_embeddings[1]

array([ 0.05734276, -0.00444569, -0.01842832, -0.04888012, -0.0126824 ,
       -0.01242457, -0.01927616, -0.00615985, -0.00271222, -0.01432896,
        0.00992631, -0.00701645,  0.02180663, -0.00301681,  0.02969918,
        0.01669667, -0.01098002,  0.03230762,  0.00334752, -0.01337908,
        0.01116903, -0.03530829,  0.01673326, -0.00447464,  0.03999374,
       -0.02915888, -0.08047061,  0.01718078,  0.04085751, -0.03472092,
       -0.05720627, -0.00432936,  0.02667969, -0.09567278, -0.01558381,
        0.04359967, -0.00835399, -0.00232975, -0.01083567, -0.04735391,
        0.03460455,  0.04132891, -0.00798295, -0.03160178,  0.02273749,
        0.02089943,  0.02054448, -0.02983005, -0.00201594,  0.00908523,
        0.04853591, -0.01340161,  0.01217945,  0.00253164, -0.05022464,
       -0.03818154, -0.03415976,  0.02487385,  0.00759243, -0.03884072,
       -0.04581745,  0.00716193, -0.01866025, -0.01307869, -0.00712307,
        0.02688209, -0.01289917,  0.00405264,  0.04389997, -0.01

In [ ]:
data = np.unique(result)

In [ ]:
data

array([0.        , 0.02183662, 0.02222047, ..., 0.95932844, 0.98216966,
       1.        ])

In [ ]:
len(data)

359412

CODE 2

https://gist.github.com/b1nch3f/13dcbfae08be2ae9400e1ab063bde809

In [ ]:
print(len(combined_list))

26747


In [ ]:
corpus = combined_list[0:1000]

In [ ]:
corpus

In [ ]:
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [ ]:
def remove_stop_words(corpus):
    stop_words = stopwords.words('english')
    results = []
    for text in corpus:
        tmp = text.split(' ')
        for stop_word in stop_words:
            if stop_word in tmp:
                tmp.remove(stop_word)
        results.append(" ".join(tmp))

    return results

In [ ]:
corpus

In [ ]:
words = []
for text in corpus:
    for word in text.split(' '):
        words.append(word)

words = set(words)

In [ ]:
word2int = {}

for i,word in enumerate(words):
    word2int[word] = i

data = []
for idx, sentence in enumerate(corpus):
    for word in sentence.split():
        data.append([idx, word])

In [ ]:
df = pd.DataFrame(data, columns = ['pid', 'label'])
df.head(10)

pid            label
0    0    investigation
1    0  characteristics
2    0    biocomposites
3    0          coating
4    0       biomedical
5    0         implants
6    0          surface
7    0            vital
8    0         function
9    0           tissue

In [ ]:
df.shape

(15407, 2)

In [ ]:
ONE_HOT_DIM_DOC = len(corpus)
ONE_HOT_DIM_DOC

1000

In [ ]:
ONE_HOT_DIM_WORD = len(words)
ONE_HOT_DIM_WORD

4801

In [ ]:
# function to convert numbers to one hot vectors
def to_one_hot_encoding(data_point_index, ONE_HOT_DIM):
    one_hot_encoding = np.zeros(ONE_HOT_DIM)
    one_hot_encoding[data_point_index] = 1
    return one_hot_encoding

In [ ]:
def data_generator(df, one_hot_dim_doc, one_hot_dim_word, word2int):
    for x, y in zip(df['pid'], df['label']):
        yield to_one_hot_encoding(x, one_hot_dim_doc), to_one_hot_encoding(word2int[y], one_hot_dim_word)

# Usage example:
X = []
Y = []
for x, y in data_generator(df, ONE_HOT_DIM_DOC, ONE_HOT_DIM_WORD, word2int):
    X.append(x)
    Y.append(y)

In [ ]:
# convert them to numpy arrays
X = np.asarray(X)
y = np.asarray(Y)

In [ ]:
def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    # The examples are read at random, in no particular order
    random.shuffle(indices)
    for i in range(0, num_examples, batch_size):
        j = tf.constant(indices[i: min(i + batch_size, num_examples)])
        yield tf.gather(features, j), tf.gather(labels, j)

In [ ]:
batch_size = 10

for X, y in data_iter(batch_size, X, y):
    print(X, '\n', y)
    break

tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(10, 1000), dtype=float64) 
 tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(10, 4801), dtype=float64)


In [ ]:
# Initializing Model Parameters
para_size = len(corpus)
vocab_size = len(words)
num_hiddens = 10

W1 = tf.Variable(tf.random.normal(shape=(para_size, num_hiddens), mean=0, stddev=0.01))
W2 = tf.Variable(tf.random.normal(shape=(num_hiddens, vocab_size), mean=0, stddev=0.01))

params = [W1, W2]

In [ ]:
# Softmax Activation
def softmax(X):
    X_exp = tf.exp(X)
    partition = tf.reduce_sum(X_exp, 1, keepdims=True)
    return X_exp / partition

In [ ]:
# Forward Propagation
def net(X):
    X = tf.reshape(tf.cast(X, dtype=tf.float32), (-1, para_size))
    a1 = tf.matmul(X, W1)
    a2 = tf.matmul(a1, W2)
    return softmax(a2)

In [ ]:
# Loss Function
def cross_entropy(y_hat, y):
    return -tf.math.log(tf.boolean_mask(y_hat, y))

In [ ]:
# Optimization
def sgd(params, grads, lr, batch_size):
    """Minibatch stochastic gradient descent.
    Defined in :numref:`sec_linear_scratch`"""
    for param, grad in zip(params, grads):
        param.assign_sub(lr*grad/batch_size)

In [ ]:
# Training
num_epochs = 10
lr = 0.1
loss = cross_entropy

for epoch in range(num_epochs):
    for X, y in data_iter(batch_size, X, y):
        # Compute gradients and update parameters
        with tf.GradientTape() as tape:
            y_hat = net(X)
            l = loss(y_hat, y)
        # Compute gradient on l with respect to [`w`, `b`]
        grads = tape.gradient(l, params)
        # Update parameters using their gradient
        sgd(params, grads, lr, batch_size)

In [ ]:
vectors = W1.numpy()
vectors[0:5]

array([[ 0.00165813, -0.00040552, -0.01096095,  0.02029846,  0.00058648,
        -0.00218436,  0.01354778, -0.00597002,  0.00568486, -0.00575738],
       [-0.01015021,  0.00203624,  0.00598121, -0.00126758, -0.00886476,
         0.00732347,  0.00339794,  0.01582761,  0.0162759 , -0.02117119],
       [ 0.00071518,  0.00158902, -0.00115005,  0.00529776, -0.00600697,
         0.01459289, -0.01654943,  0.00611146,  0.0043891 ,  0.00667281],
       [-0.02381264,  0.00226682,  0.0042288 ,  0.007755  , -0.01272931,
         0.01048362, -0.00061596, -0.01060449,  0.00896199,  0.00922523],
       [-0.00074815,  0.00844054, -0.00178332, -0.00373073, -0.01688201,
        -0.01166729, -0.01341521, -0.01312302, -0.01502402,  0.00714719]],
      dtype=float32)

In [ ]:
p2v_df = pd.DataFrame(vectors)

In [ ]:
p2v_df['para'] = corpus
p2v_df

0         1         2         3         4         5         6  \
0    0.001658 -0.000406 -0.010961  0.020298  0.000586 -0.002184  0.013548   
1   -0.010150  0.002036  0.005981 -0.001268 -0.008865  0.007323  0.003398   
2    0.000715  0.001589 -0.001150  0.005298 -0.006007  0.014593 -0.016549   
3   -0.023813  0.002267  0.004229  0.007755 -0.012729  0.010484 -0.000616   
4   -0.000748  0.008441 -0.001783 -0.003731 -0.016882 -0.011667 -0.013415   
..        ...       ...       ...       ...       ...       ...       ...   
995 -0.025961 -0.001814 -0.008841 -0.003096  0.002801 -0.009122  0.008212   
996  0.002769 -0.002499  0.025276  0.021966 -0.011601 -0.006806 -0.027298   
997 -0.016466 -0.011339  0.003614 -0.002773  0.003766 -0.005364  0.001009   
998  0.005739 -0.006983 -0.001411 -0.003331 -0.007469  0.005175 -0.005487   
999  0.001955 -0.011194 -0.016931 -0.009253  0.014282  0.004621  0.002543   

            7         8         9  \
0   -0.005970  0.005685 -0.005757   
1    0.015828  0.016276 -0.021171   
2    0.006111  0.004389  0.006673   
3   -0.010604  0.008962  0.009225   
4   -0.013123 -0.015024  0.007147   
..        ...       ...       ...   
995  0.016887  0.017102  0.001052   
996 -0.005454 -0.005876  0.008541   
997 -0.022676  0.000959  0.000987   
998  0.027153  0.007008  0.000566   
999  0.001298 -0.006415  0.008531   

                                                  para  
0    investigation characteristics biocomposites co...  
1    surface modification coatings adjusted provide...  
2    coatings increase corrosion resistance reducin...  
3    fabricated polymer based bio composite coating...  
4    coatings ’ surface morphology phases studied u...  
..                                                 ...  
995  parameters take account values coefficients ch...  
996  set values parameters range varying possible v...  
997  influence number planetary gears simple planet...  
998  based function analogue equivalent moment iner...  
999  keywords simple james planetary mechanism mech...  

[1000 rows x 11 columns]

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
x = p2v_df.iloc[0:10, 0:10]
x

0         1         2         3         4         5         6  \
0  0.001658 -0.000406 -0.010961  0.020298  0.000586 -0.002184  0.013548   
1 -0.010150  0.002036  0.005981 -0.001268 -0.008865  0.007323  0.003398   
2  0.000715  0.001589 -0.001150  0.005298 -0.006007  0.014593 -0.016549   
3 -0.023813  0.002267  0.004229  0.007755 -0.012729  0.010484 -0.000616   
4 -0.000748  0.008441 -0.001783 -0.003731 -0.016882 -0.011667 -0.013415   
5 -0.003553  0.005549 -0.007009  0.011124  0.004171  0.010067 -0.003269   
6  0.010115  0.003357  0.007225 -0.010898 -0.005469 -0.005922 -0.015124   
7  0.009012  0.019040  0.009301  0.005959 -0.002589  0.001694  0.025823   
8  0.005400  0.015464  0.016020  0.000176 -0.009932  0.010734  0.010707   
9 -0.000505  0.018541 -0.006445 -0.017326  0.003571 -0.006027  0.010663   

          7         8         9  
0 -0.005970  0.005685 -0.005757  
1  0.015828  0.016276 -0.021171  
2  0.006111  0.004389  0.006673  
3 -0.010604  0.008962  0.009225  
4 -0.013123 -0.015024  0.007147  
5 -0.017244 -0.003866 -0.006944  
6  0.007749 -0.004396  0.018024  
7 -0.001168 -0.005246  0.002411  
8 -0.006187 -0.005361  0.002724  
9 -0.006283  0.002678  0.004928

In [ ]:
y = p2v_df.iloc[0:10, 0:10]
print(type(y))
y

<class 'pandas.core.frame.DataFrame'>


0         1         2         3         4         5         6  \
0  0.001658 -0.000406 -0.010961  0.020298  0.000586 -0.002184  0.013548   
1 -0.010150  0.002036  0.005981 -0.001268 -0.008865  0.007323  0.003398   
2  0.000715  0.001589 -0.001150  0.005298 -0.006007  0.014593 -0.016549   
3 -0.023813  0.002267  0.004229  0.007755 -0.012729  0.010484 -0.000616   
4 -0.000748  0.008441 -0.001783 -0.003731 -0.016882 -0.011667 -0.013415   
5 -0.003553  0.005549 -0.007009  0.011124  0.004171  0.010067 -0.003269   
6  0.010115  0.003357  0.007225 -0.010898 -0.005469 -0.005922 -0.015124   
7  0.009012  0.019040  0.009301  0.005959 -0.002589  0.001694  0.025823   
8  0.005400  0.015464  0.016020  0.000176 -0.009932  0.010734  0.010707   
9 -0.000505  0.018541 -0.006445 -0.017326  0.003571 -0.006027  0.010663   

          7         8         9  
0 -0.005970  0.005685 -0.005757  
1  0.015828  0.016276 -0.021171  
2  0.006111  0.004389  0.006673  
3 -0.010604  0.008962  0.009225  
4 -0.013123 -0.015024  0.007147  
5 -0.017244 -0.003866 -0.006944  
6  0.007749 -0.004396  0.018024  
7 -0.001168 -0.005246  0.002411  
8 -0.006187 -0.005361  0.002724  
9 -0.006283  0.002678  0.004928

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
sim = cosine_similarity(x, y)
sim

array([[ 1.        ,  0.03524692, -0.2566709 ,  0.09355422, -0.28394142,
         0.46067676, -0.7277936 ,  0.32557818, -0.07175939, -0.12094805],
       [ 0.03524692,  1.        ,  0.12482536,  0.18926379, -0.474045  ,
        -0.18277404, -0.37468982, -0.02881634,  0.03009968, -0.16165893],
       [-0.2566709 ,  0.12482536,  1.0000001 ,  0.33627898,  0.05767971,
         0.11826679,  0.36307377, -0.37526774,  0.00880689, -0.43106025],
       [ 0.09355422,  0.18926379,  0.33627898,  0.9999998 ,  0.14690076,
         0.31760508, -0.20779711, -0.05126385,  0.2374797 , -0.08249509],
       [-0.28394142, -0.474045  ,  0.05767971,  0.14690076,  1.0000001 ,
         0.12400796,  0.47834277, -0.0795783 ,  0.17243662,  0.17336534],
       [ 0.46067676, -0.18277404,  0.11826679,  0.31760508,  0.12400796,
         1.0000001 , -0.5569848 ,  0.02132572,  0.11911755, -0.07413369],
       [-0.7277936 , -0.37468982,  0.36307377, -0.20779711,  0.47834277,
        -0.5569848 ,  1.        , -0.15322435

In [ ]:
for row in range(sim.shape[0]):
    src = p2v_df.iloc[[row]]['para'].to_string(index=False)
    tmp = np.argsort(sim[row])
    tgt = p2v_df.iloc[[tmp[0]]]['para'].to_string(index=False)
    print(f'{src} -> {tgt}')

investigation characteristics biocomposites coa... -> antibacterial activity functionalized coatings ...
surface modification coatings adjusted provide ... -> coatings ’ surface morphology phases studied us...
coatings increase corrosion resistance reducing... -> contact angle results showed highly hydrophilic...
fabricated polymer based bio composite coatings... -> antibacterial activity functionalized coatings ...
coatings ’ surface morphology phases studied us... -> surface modification coatings adjusted provide ...
wettability behavior coated samples also studie... -> antibacterial activity functionalized coatings ...
antibacterial activity functionalized coatings ... -> investigation characteristics biocomposites coa...
ftir results showed blending chi alg nanopartic... -> coatings increase corrosion resistance reducing...
sem results demonstrated coating layers uniform... -> investigation characteristics biocomposites coa...
contact angle results showed highly hydrophilic... -> c